-- MySQL Script generated by MySQL Workbench
-- 10/01/14 09:34:07
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema my_tracker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `my_tracker` ;
CREATE SCHEMA IF NOT EXISTS `my_tracker` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `my_tracker` ;

-- -----------------------------------------------------
-- Table `my_tracker`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_tracker`.`recipes` ;

CREATE TABLE IF NOT EXISTS `my_tracker`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recipe` VARCHAR(255) NULL DEFAULT NULL,
  `points` INT NULL DEFAULT 0,
  `time` VARCHAR(45) NULL DEFAULT NULL,
  `pic` VARCHAR(255) NULL DEFAULT NULL,
  `preparation` TEXT NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_tracker`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_tracker`.`users` ;

CREATE TABLE IF NOT EXISTS `my_tracker`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` TEXT NOT NULL,
  `avatar` VARCHAR(255) NULL,
  `api_key` VARCHAR(32) NULL,
  `user_status` INT NOT NULL,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_tracker`.`tracker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_tracker`.`tracker` ;

CREATE TABLE IF NOT EXISTS `my_tracker`.`tracker` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `exercise` VARCHAR(128) NULL DEFAULT NULL,
  `minutes` INT NULL DEFAULT 0,
  `exercise_points` INT NULL,
  `weight` FLOAT NULL DEFAULT 0.0,
  `breakfast` VARCHAR(128) NULL DEFAULT NULL,
  `breakfast_points` INT NULL DEFAULT 0,
  `lunch` VARCHAR(128) NULL DEFAULT NULL,
  `lunch_points` INT NULL DEFAULT 0,
  `dinner` VARCHAR(128) NULL DEFAULT NULL,
  `dinner_points` INT NULL DEFAULT 0,
  `snacks` VARCHAR(128) NULL DEFAULT NULL,
  `snacks_points` INT NULL DEFAULT 0,
  `indulgence` VARCHAR(128) NULL DEFAULT NULL,
  `indulgence_points` INT NULL DEFAULT 0,
  `users_id` INT(11) NOT NULL,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_tracker_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_tracker_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `my_tracker`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_tracker`.`reset_pw`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_tracker`.`reset_pw` ;

CREATE TABLE IF NOT EXISTS `my_tracker`.`reset_pw` (
  `uniq_hash` TEXT NOT NULL,
  `users_id` INT(11) NOT NULL,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_reset_pw_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_reset_pw_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `my_tracker`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_tracker`.`activate_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_tracker`.`activate_user` ;

CREATE TABLE IF NOT EXISTS `my_tracker`.`activate_user` (
  `uniq_hash` TEXT NOT NULL,
  `users_id` INT(11) NOT NULL,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_activate_user_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_activate_user_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `my_tracker`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_tracker`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_tracker`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `my_tracker`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingredient` VARCHAR(255) NULL DEFAULT NULL,
  `department` VARCHAR(128) NULL DEFAULT NULL,
  `islenumber` INT NULL DEFAULT 0,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_tracker`.`recipes_has_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_tracker`.`recipes_has_ingredients` ;

CREATE TABLE IF NOT EXISTS `my_tracker`.`recipes_has_ingredients` (
  `recipes_id` INT NOT NULL,
  `ingredients_id` INT NOT NULL,
  PRIMARY KEY (`recipes_id`, `ingredients_id`),
  INDEX `fk_recipes_has_ingredients_ingredients1_idx` (`ingredients_id` ASC),
  INDEX `fk_recipes_has_ingredients_recipes1_idx` (`recipes_id` ASC),
  CONSTRAINT `fk_recipes_has_ingredients_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `my_tracker`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipes_has_ingredients_ingredients1`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `my_tracker`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_tracker`.`users_has_recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_tracker`.`users_has_recipes` ;

CREATE TABLE IF NOT EXISTS `my_tracker`.`users_has_recipes` (
  `users_id` INT(11) NOT NULL,
  `recipes_id` INT NOT NULL,
  `created_date` TIMESTAMP NULL DEFAULT NULL,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`users_id`, `recipes_id`),
  INDEX `fk_users_has_recipes_recipes1_idx` (`recipes_id` ASC),
  INDEX `fk_users_has_recipes_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_recipes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `my_tracker`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_recipes_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `my_tracker`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
